export interface ColorItem {
  name: string;
  hex: string;
  category: string;
}

export const colorData: ColorItem[] = [
  // Red colors (expanded to 85 colors)
  { name: 'Amaranth', hex: '#e52b50', category: 'Red' },
  { name: 'Amaranth purple', hex: '#ab274f', category: 'Red' },
  { name: 'Barn red', hex: '#7c0a02', category: 'Red' },
  { name: 'Bittersweet', hex: '#ff6347', category: 'Red' },
  { name: 'Bittersweet shimmer', hex: '#bf4f36', category: 'Red' },
  { name: 'Blood red', hex: '#660000', category: 'Red' },
  { name: 'Brick red', hex: '#cb4154', category: 'Red' },
  { name: 'Bright pink (Crayola)', hex: '#ff007f', category: 'Red' },
  { name: 'Burgundy', hex: '#800020', category: 'Red' },
  { name: 'Cadmium red', hex: '#e30022', category: 'Red' },
  { name: 'Candy apple red', hex: '#ff0800', category: 'Red' },
  { name: 'Cantaloupe melon', hex: '#fdbcb4', category: 'Red' },
  { name: 'Cardinal', hex: '#c41e3a', category: 'Red' },
  { name: 'Carmine', hex: '#960018', category: 'Red' },
  { name: 'Carmine pink', hex: '#eb4c42', category: 'Red' },
  { name: 'Carnelian', hex: '#b31b1b', category: 'Red' },
  { name: 'Cerise', hex: '#de3163', category: 'Red' },
  { name: 'Cherry', hex: '#de3163', category: 'Red' },
  { name: 'Cherry red', hex: '#d2001f', category: 'Red' },
  { name: 'Chestnut red', hex: '#bc3f4a', category: 'Red' },
  { name: 'Chili red', hex: '#c21807', category: 'Red' },
  { name: 'Chinese red', hex: '#aa381e', category: 'Red' },
  { name: 'Chocolate cosmos', hex: '#58111a', category: 'Red' },
  { name: 'Cinnabar', hex: '#e34234', category: 'Red' },
  { name: 'Claret', hex: '#7f1734', category: 'Red' },
  { name: 'Cochineal', hex: '#8c2d19', category: 'Red' },
  { name: 'Coquelicot', hex: '#ff3800', category: 'Red' },
  { name: 'Coral', hex: '#ff7f50', category: 'Red' },
  { name: 'Coral pink', hex: '#f88379', category: 'Red' },
  { name: 'Coral red', hex: '#ff4040', category: 'Red' },
  { name: 'Cordovan', hex: '#893f45', category: 'Red' },
  { name: 'Cornell red', hex: '#b31b1b', category: 'Red' },
  { name: 'Crimson', hex: '#dc143c', category: 'Red' },
  { name: 'Crimson glory', hex: '#be0032', category: 'Red' },
  { name: 'Dark coral', hex: '#cd5b45', category: 'Red' },
  { name: 'Dark red', hex: '#8b0000', category: 'Red' },
  { name: 'Dark salmon', hex: '#e9967a', category: 'Red' },
  { name: 'Dark scarlet', hex: '#560319', category: 'Red' },
  { name: 'Deep carmine', hex: '#a9203e', category: 'Red' },
  { name: 'Deep red', hex: '#850101', category: 'Red' },
  { name: 'English red', hex: '#ab4b52', category: 'Red' },
  { name: 'Falu red', hex: '#801818', category: 'Red' },
  { name: 'Ferrari red', hex: '#ff2800', category: 'Red' },
  { name: 'Fire brick', hex: '#b22222', category: 'Red' },
  { name: 'Fire engine red', hex: '#ce2029', category: 'Red' },
  { name: 'Flame', hex: '#e25822', category: 'Red' },
  { name: 'Flamingo pink', hex: '#fc8eac', category: 'Red' },
  { name: 'Folly', hex: '#ff004f', category: 'Red' },
  { name: 'Fuzzy wuzzy', hex: '#cc6666', category: 'Red' },
  { name: 'Garnet', hex: '#733635', category: 'Red' },
  { name: 'Geranium', hex: '#c1272d', category: 'Red' },
  { name: 'Hibiscus', hex: '#b43757', category: 'Red' },
  { name: 'Imperial red', hex: '#ed2939', category: 'Red' },
  { name: 'Indian red', hex: '#cd5c5c', category: 'Red' },
  { name: 'Jasper', hex: '#d73502', category: 'Red' },
  { name: 'Light coral', hex: '#f08080', category: 'Red' },
  { name: 'Light red', hex: '#ffcccb', category: 'Red' },
  { name: 'Light salmon', hex: '#ffa07a', category: 'Red' },
  { name: 'Madder', hex: '#cc0000', category: 'Red' },
  { name: 'Mahogany', hex: '#c04000', category: 'Red' },
  { name: 'Maroon', hex: '#800000', category: 'Red' },
  { name: 'Medium carmine', hex: '#af4035', category: 'Red' },
  { name: 'Misty rose', hex: '#ffe4e1', category: 'Red' },
  { name: 'Neon red', hex: '#ff073a', category: 'Red' },
  { name: 'Off Red (RGB)', hex: '#ff0040', category: 'Red' },
  { name: 'Old rose', hex: '#c08081', category: 'Red' },
  { name: 'Old crimson', hex: '#9c2542', category: 'Red' },
  { name: 'Opera mauve', hex: '#b784a7', category: 'Red' },
  { name: 'Oxblood', hex: '#4a0e0e', category: 'Red' },
  { name: 'Pastel red', hex: '#ff6961', category: 'Red' },
  { name: 'Penn red', hex: '#9e1316', category: 'Red' },
  { name: 'Persian red', hex: '#cc3333', category: 'Red' },
  { name: 'Pink', hex: '#ffc0cb', category: 'Red' },
  { name: 'Pomegranate', hex: '#f34723', category: 'Red' },
  { name: 'Poppy', hex: '#ec5800', category: 'Red' },
  { name: 'Raspberry', hex: '#e30b5c', category: 'Red' },
  { name: 'Red', hex: '#ff0000', category: 'Red' },
  { name: 'Red Brown', hex: '#a52a2a', category: 'Red' },
  { name: 'Red devil', hex: '#860111', category: 'Red' },
  { name: 'Red (CMYK)', hex: '#ed1c24', category: 'Red' },
  { name: 'Red (Crayola)', hex: '#ee204d', category: 'Red' },
  { name: 'Red (Munsell)', hex: '#f2003c', category: 'Red' },
  { name: 'Rose red', hex: '#c21e56', category: 'Red' },
  { name: 'Ruby', hex: '#e0115f', category: 'Red' },
  { name: 'Rusty red', hex: '#da2c43', category: 'Red' },
  { name: 'Scarlet', hex: '#ff2400', category: 'Red' },
  { name: 'Tomato', hex: '#ff6347', category: 'Red' },
  { name: 'Turkey red', hex: '#a91101', category: 'Red' },
  { name: 'Vermilion', hex: '#e34234', category: 'Red' },
  { name: 'Wine', hex: '#722f37', category: 'Red' },

  // Orange colors (expanded to 55 colors)
  { name: 'Amber', hex: '#ffbf00', category: 'Orange' },
  { name: 'Apricot', hex: '#fbceb1', category: 'Orange' },
  { name: 'Atomic tangerine', hex: '#ff9966', category: 'Orange' },
  { name: 'Bittersweet orange', hex: '#fe6f5e', category: 'Orange' },
  { name: 'Blaze orange', hex: '#ff6600', category: 'Orange' },
  { name: 'Burnt orange', hex: '#cc5500', category: 'Orange' },
  { name: 'Burnt sienna', hex: '#e97451', category: 'Orange' },
  { name: 'Cadmium orange', hex: '#ed872d', category: 'Orange' },
  { name: 'Carrot orange', hex: '#ed9121', category: 'Orange' },
  { name: 'Celosia orange', hex: '#ff4500', category: 'Orange' },
  { name: 'Chrome orange', hex: '#ffa000', category: 'Orange' },
  { name: 'Chrome yellow', hex: '#ffa700', category: 'Orange' },
  { name: 'Coral', hex: '#ff7f50', category: 'Orange' },
  { name: 'Dark orange', hex: '#ff8c00', category: 'Orange' },
  { name: 'Dark salmon', hex: '#e9967a', category: 'Orange' },
  { name: 'Deep carrot orange', hex: '#e9692c', category: 'Orange' },
  { name: 'Deep peach', hex: '#ffcba4', category: 'Orange' },
  { name: 'Dutch orange', hex: '#ff8200', category: 'Orange' },
  { name: 'Flame orange', hex: '#ff5100', category: 'Orange' },
  { name: 'Gamboge', hex: '#e49b0f', category: 'Orange' },
  { name: 'Georgia peach', hex: '#ffb347', category: 'Orange' },
  { name: 'Ginger', hex: '#b06500', category: 'Orange' },
  { name: 'Heat wave', hex: '#ff7a00', category: 'Orange' },
  { name: 'Honey orange', hex: '#ff8c69', category: 'Orange' },
  { name: 'International orange', hex: '#ff4f00', category: 'Orange' },
  { name: 'Kumquat', hex: '#ffa500', category: 'Orange' },
  { name: 'Light orange', hex: '#fed8b1', category: 'Orange' },
  { name: 'Light salmon', hex: '#ffa07a', category: 'Orange' },
  { name: 'Macaroni cheese', hex: '#ffb347', category: 'Orange' },
  { name: 'Mandarin', hex: '#f37a48', category: 'Orange' },
  { name: 'Mango', hex: '#ffcc5c', category: 'Orange' },
  { name: 'Mango tango', hex: '#ff8243', category: 'Orange' },
  { name: 'Melon', hex: '#fdbcb4', category: 'Orange' },
  { name: 'Neon orange', hex: '#ff6700', category: 'Orange' },
  { name: 'Orange', hex: '#ffa500', category: 'Orange' },
  { name: 'Orange peel', hex: '#ff9f00', category: 'Orange' },
  { name: 'Orange red', hex: '#ff4500', category: 'Orange' },
  { name: 'Papaya', hex: '#ff9f00', category: 'Orange' },
  { name: 'Papaya whip', hex: '#ffefd5', category: 'Orange' },
  { name: 'Pastel orange', hex: '#ffb347', category: 'Orange' },
  { name: 'Peach', hex: '#ffcba4', category: 'Orange' },
  { name: 'Peach orange', hex: '#ffcc99', category: 'Orange' },
  { name: 'Peach puff', hex: '#ffdab9', category: 'Orange' },
  { name: 'Persian orange', hex: '#d99058', category: 'Orange' },
  { name: 'Persimmon', hex: '#ec5800', category: 'Orange' },
  { name: 'Portland orange', hex: '#ff5a36', category: 'Orange' },
  { name: 'Princeton orange', hex: '#f58025', category: 'Orange' },
  { name: 'Pumpkin', hex: '#ff7518', category: 'Orange' },
  { name: 'Red orange', hex: '#ff5349', category: 'Orange' },
  { name: 'Rust', hex: '#b7410e', category: 'Orange' },
  { name: 'Safety orange', hex: '#ff6600', category: 'Orange' },
  { name: 'Sandy brown', hex: '#f4a460', category: 'Orange' },
  { name: 'Sunset orange', hex: '#fd5e53', category: 'Orange' },
  { name: 'Tangerine', hex: '#f28500', category: 'Orange' },
  { name: 'Tiger orange', hex: '#fd6a02', category: 'Orange' },
  { name: 'Vivid orange', hex: '#ff5f00', category: 'Orange' },

  // Yellow colors (expanded to 50 colors)
  { name: 'Aureolin', hex: '#fdee00', category: 'Yellow' },
  { name: 'Banana yellow', hex: '#ffe135', category: 'Yellow' },
  { name: 'Buff', hex: '#f0dc82', category: 'Yellow' },
  { name: 'Butter', hex: '#ffdb58', category: 'Yellow' },
  { name: 'Canary', hex: '#ffef00', category: 'Yellow' },
  { name: 'Canary yellow', hex: '#ffef00', category: 'Yellow' },
  { name: 'Champagne', hex: '#fad5a5', category: 'Yellow' },
  { name: 'Chartreuse', hex: '#7fff00', category: 'Yellow' },
  { name: 'Chrome yellow', hex: '#ffa700', category: 'Yellow' },
  { name: 'Citrine', hex: '#e4d00a', category: 'Yellow' },
  { name: 'Citron', hex: '#9fa91f', category: 'Yellow' },
  { name: 'Corn', hex: '#fbec5d', category: 'Yellow' },
  { name: 'Cream', hex: '#fffdd0', category: 'Yellow' },
  { name: 'Daffodil', hex: '#ffff31', category: 'Yellow' },
  { name: 'Dark goldenrod', hex: '#b8860b', category: 'Yellow' },
  { name: 'Dark khaki', hex: '#bdb76b', category: 'Yellow' },
  { name: 'Electric lime', hex: '#ccff00', category: 'Yellow' },
  { name: 'Electric yellow', hex: '#ffff33', category: 'Yellow' },
  { name: 'Flax', hex: '#eedc82', category: 'Yellow' },
  { name: 'Flavescent', hex: '#f7e98e', category: 'Yellow' },
  { name: 'Gold', hex: '#ffd700', category: 'Yellow' },
  { name: 'Golden yellow', hex: '#ffdf00', category: 'Yellow' },
  { name: 'Goldenrod', hex: '#daa520', category: 'Yellow' },
  { name: 'Honey', hex: '#feb811', category: 'Yellow' },
  { name: 'Icterine', hex: '#fcf75e', category: 'Yellow' },
  { name: 'Ivory', hex: '#fffff0', category: 'Yellow' },
  { name: 'Jasmine', hex: '#f8de7e', category: 'Yellow' },
  { name: 'Jonquil', hex: '#fada5e', category: 'Yellow' },
  { name: 'Khaki', hex: '#f0e68c', category: 'Yellow' },
  { name: 'Lemon', hex: '#fff700', category: 'Yellow' },
  { name: 'Lemon chiffon', hex: '#fffacd', category: 'Yellow' },
  { name: 'Light goldenrod', hex: '#fafad2', category: 'Yellow' },
  { name: 'Light yellow', hex: '#ffffe0', category: 'Yellow' },
  { name: 'Lime', hex: '#bfff00', category: 'Yellow' },
  { name: 'Maize', hex: '#fbec5d', category: 'Yellow' },
  { name: 'Mellow yellow', hex: '#f8de7e', category: 'Yellow' },
  { name: 'Mimosa', hex: '#efc050', category: 'Yellow' },
  { name: 'Mustard', hex: '#ffdb58', category: 'Yellow' },
  { name: 'Naples yellow', hex: '#fada5e', category: 'Yellow' },
  { name: 'Navajo white', hex: '#ffdead', category: 'Yellow' },
  { name: 'Old gold', hex: '#cfb53b', category: 'Yellow' },
  { name: 'Pale goldenrod', hex: '#eee8aa', category: 'Yellow' },
  { name: 'Peach yellow', hex: '#fadfad', category: 'Yellow' },
  { name: 'Pear', hex: '#d1e231', category: 'Yellow' },
  { name: 'Royal yellow', hex: '#fada5e', category: 'Yellow' },
  { name: 'Saffron', hex: '#f4c430', category: 'Yellow' },
  { name: 'School bus yellow', hex: '#ffd800', category: 'Yellow' },
  { name: 'Straw', hex: '#e4d96f', category: 'Yellow' },
  { name: 'Vanilla', hex: '#f3e5ab', category: 'Yellow' },
  { name: 'Wheat', hex: '#f5deb3', category: 'Yellow' },
  { name: 'Yellow', hex: '#ffff00', category: 'Yellow' },

  // Green colors (expanded)
  { name: 'Absinthe', hex: '#74c365', category: 'Green' },
  { name: 'Acid green', hex: '#b0bf1a', category: 'Green' },
  { name: 'Algae green', hex: '#64e986', category: 'Green' },
  { name: 'Amazon', hex: '#3b7a57', category: 'Green' },
  { name: 'Android green', hex: '#a4c639', category: 'Green' },
  { name: 'Apple green', hex: '#8db600', category: 'Green' },
  { name: 'Army green', hex: '#4b5320', category: 'Green' },
  { name: 'Artichoke', hex: '#8f9779', category: 'Green' },
  { name: 'Asparagus', hex: '#87a96b', category: 'Green' },
  { name: 'Avocado', hex: '#568203', category: 'Green' },
  { name: 'Bamboo', hex: '#c7cc9a', category: 'Green' },
  { name: 'Basil', hex: '#8a9a5b', category: 'Green' },
  { name: 'Bottle green', hex: '#006a4e', category: 'Green' },
  { name: 'British racing green', hex: '#004225', category: 'Green' },
  { name: 'Brunswick green', hex: '#1b4332', category: 'Green' },
  { name: 'Cadmium green', hex: '#006b3c', category: 'Green' },
  { name: 'Cambridge blue', hex: '#a3c1ad', category: 'Green' },
  { name: 'Celadon', hex: '#ace1af', category: 'Green' },
  { name: 'Chartreuse', hex: '#7fff00', category: 'Green' },
  { name: 'Chartreuse green', hex: '#7fff00', category: 'Green' },
  { name: 'Chrome green', hex: '#00573f', category: 'Green' },
  { name: 'Clover', hex: '#3ea055', category: 'Green' },
  { name: 'Conifer', hex: '#acdd4d', category: 'Green' },
  { name: 'Dartmouth green', hex: '#00703c', category: 'Green' },
  { name: 'Dark green', hex: '#006400', category: 'Green' },
  { name: 'Dark olive green', hex: '#556b2f', category: 'Green' },
  { name: 'Dark pastel green', hex: '#03c03c', category: 'Green' },
  { name: 'Dark sea green', hex: '#8fbc8f', category: 'Green' },
  { name: 'Electric green', hex: '#00ff00', category: 'Green' },
  { name: 'Emerald', hex: '#50c878', category: 'Green' },
  { name: 'Eucalyptus', hex: '#44d7a8', category: 'Green' },
  { name: 'Fern green', hex: '#4f7942', category: 'Green' },
  { name: 'Forest green', hex: '#228b22', category: 'Green' },
  { name: 'Go green', hex: '#00ab66', category: 'Green' },
  { name: 'Grass green', hex: '#7cfc00', category: 'Green' },
  { name: 'Green', hex: '#008000', category: 'Green' },
  { name: 'Green apple', hex: '#4cc417', category: 'Green' },
  { name: 'Green pea', hex: '#4dffb8', category: 'Green' },
  { name: 'Harlequin', hex: '#3fff00', category: 'Green' },
  { name: 'Hooker green', hex: '#49796b', category: 'Green' },
  { name: 'Hunter green', hex: '#355e3b', category: 'Green' },
  { name: 'India green', hex: '#138808', category: 'Green' },
  { name: 'Islamic green', hex: '#009000', category: 'Green' },
  { name: 'Jade', hex: '#00a86b', category: 'Green' },
  { name: 'Jungle green', hex: '#29ab87', category: 'Green' },
  { name: 'Kelly green', hex: '#4cbb17', category: 'Green' },
  { name: 'Kiwi', hex: '#8ee53f', category: 'Green' },
  { name: 'Lawn green', hex: '#7cfc00', category: 'Green' },
  { name: 'Leaf green', hex: '#5caa15', category: 'Green' },
  { name: 'Light green', hex: '#90ee90', category: 'Green' },
  { name: 'Light sea green', hex: '#20b2aa', category: 'Green' },
  { name: 'Lime', hex: '#00ff00', category: 'Green' },
  { name: 'Lime green', hex: '#32cd32', category: 'Green' },
  { name: 'Lincoln green', hex: '#195905', category: 'Green' },
  { name: 'Malachite', hex: '#0bda51', category: 'Green' },
  { name: 'May green', hex: '#4c9141', category: 'Green' },
  { name: 'Medium green', hex: '#00fa54', category: 'Green' },
  { name: 'Medium sea green', hex: '#3cb371', category: 'Green' },
  { name: 'Medium spring green', hex: '#00fa9a', category: 'Green' },
  { name: 'Military green', hex: '#667c3e', category: 'Green' },
  { name: 'Mint', hex: '#3eb489', category: 'Green' },
  { name: 'Mint cream', hex: '#f5fffa', category: 'Green' },
  { name: 'Mint green', hex: '#98fb98', category: 'Green' },
  { name: 'Moss green', hex: '#addfad', category: 'Green' },
  { name: 'Myrtle', hex: '#21421e', category: 'Green' },
  { name: 'Neon green', hex: '#39ff14', category: 'Green' },
  { name: 'Office green', hex: '#008000', category: 'Green' },
  { name: 'Olive', hex: '#808000', category: 'Green' },
  { name: 'Olive drab', hex: '#6b8e23', category: 'Green' },
  { name: 'Pakistan green', hex: '#006600', category: 'Green' },
  { name: 'Pale green', hex: '#98fb98', category: 'Green' },
  { name: 'Paris green', hex: '#50c878', category: 'Green' },
  { name: 'Pastel green', hex: '#77dd77', category: 'Green' },
  { name: 'Pea green', hex: '#8ebc00', category: 'Green' },
  { name: 'Persian green', hex: '#00a693', category: 'Green' },
  { name: 'Phthalo green', hex: '#123524', category: 'Green' },
  { name: 'Pine green', hex: '#01796f', category: 'Green' },
  { name: 'Pistachio', hex: '#93c572', category: 'Green' },
  { name: 'Racing green', hex: '#014421', category: 'Green' },
  { name: 'Reseda green', hex: '#6c7c32', category: 'Green' },
  { name: 'Rifle green', hex: '#414833', category: 'Green' },
  { name: 'Russian green', hex: '#679267', category: 'Green' },
  { name: 'Sage', hex: '#9caf88', category: 'Green' },
  { name: 'Sap green', hex: '#507d2a', category: 'Green' },
  { name: 'Sea green', hex: '#2e8b57', category: 'Green' },
  { name: 'Shamrock green', hex: '#009e60', category: 'Green' },
  { name: 'Spring bud', hex: '#a7fc00', category: 'Green' },
  { name: 'Spring green', hex: '#00ff7f', category: 'Green' },
  { name: 'Tea green', hex: '#d0f0c0', category: 'Green' },
  { name: 'Teal green', hex: '#00827f', category: 'Green' },
  { name: 'Turquoise green', hex: '#a0d6b4', category: 'Green' },
  { name: 'Viridian', hex: '#40826d', category: 'Green' },
  { name: 'Yellow green', hex: '#9acd32', category: 'Green' },
  { name: 'Zombie green', hex: '#54c571', category: 'Green' },

  // Blue colors (expanded to 90 colors)
  { name: 'Air Force blue', hex: '#5d8aa8', category: 'Blue' },
  { name: 'Alice blue', hex: '#f0f8ff', category: 'Blue' },
  { name: 'Azure', hex: '#007fff', category: 'Blue' },
  { name: 'Baby blue', hex: '#89cff0', category: 'Blue' },
  { name: 'Blue', hex: '#0000ff', category: 'Blue' },
  { name: 'Blue bell', hex: '#a2a2d0', category: 'Blue' },
  { name: 'Blue gray', hex: '#6699cc', category: 'Blue' },
  { name: 'Blue sapphire', hex: '#126180', category: 'Blue' },
  { name: 'Blueberry', hex: '#4f86f7', category: 'Blue' },
  { name: 'Bondi blue', hex: '#0095b6', category: 'Blue' },
  { name: 'Brandeis blue', hex: '#0070ff', category: 'Blue' },
  { name: 'Cambridge blue', hex: '#a3c1ad', category: 'Blue' },
  { name: 'Cadet blue', hex: '#5f9ea0', category: 'Blue' },
  { name: 'Capri', hex: '#00bfff', category: 'Blue' },
  { name: 'Carolina blue', hex: '#56a0d3', category: 'Blue' },
  { name: 'Celestial blue', hex: '#4997d0', category: 'Blue' },
  { name: 'Cerulean', hex: '#007ba7', category: 'Blue' },
  { name: 'Cerulean blue', hex: '#2a52be', category: 'Blue' },
  { name: 'Cobalt blue', hex: '#0047ab', category: 'Blue' },
  { name: 'Columbia blue', hex: '#9bddff', category: 'Blue' },
  { name: 'Cornflower blue', hex: '#6495ed', category: 'Blue' },
  { name: 'Crystal blue', hex: '#68a0b0', category: 'Blue' },
  { name: 'Cyan', hex: '#00ffff', category: 'Blue' },
  { name: 'Dark blue', hex: '#00008b', category: 'Blue' },
  { name: 'Dark cyan', hex: '#008b8b', category: 'Blue' },
  { name: 'Dark powder blue', hex: '#003399', category: 'Blue' },
  { name: 'Dark slate blue', hex: '#483d8b', category: 'Blue' },
  { name: 'Dark turquoise', hex: '#00ced1', category: 'Blue' },
  { name: 'Deep blue', hex: '#040f75', category: 'Blue' },
  { name: 'Deep sky blue', hex: '#00bfff', category: 'Blue' },
  { name: 'Denim', hex: '#1560bd', category: 'Blue' },
  { name: 'Dodger blue', hex: '#1e90ff', category: 'Blue' },
  { name: 'Duke blue', hex: '#00009c', category: 'Blue' },
  { name: 'Egyptian blue', hex: '#1034a6', category: 'Blue' },
  { name: 'Electric blue', hex: '#7df9ff', category: 'Blue' },
  { name: 'French blue', hex: '#0072bb', category: 'Blue' },
  { name: 'Glaucous', hex: '#6082b6', category: 'Blue' },
  { name: 'Han blue', hex: '#446ccf', category: 'Blue' },
  { name: 'Ice blue', hex: '#99d9ea', category: 'Blue' },
  { name: 'International Klein Blue', hex: '#002fa7', category: 'Blue' },
  { name: 'Iris', hex: '#5a4fcf', category: 'Blue' },
  { name: 'Light blue', hex: '#add8e6', category: 'Blue' },
  { name: 'Light cyan', hex: '#e0ffff', category: 'Blue' },
  { name: 'Light sky blue', hex: '#87cefa', category: 'Blue' },
  { name: 'Light slate blue', hex: '#8470ff', category: 'Blue' },
  { name: 'Light steel blue', hex: '#b0c4de', category: 'Blue' },
  { name: 'Lapis lazuli', hex: '#26619c', category: 'Blue' },
  { name: 'Maya blue', hex: '#73c2fb', category: 'Blue' },
  { name: 'Medium blue', hex: '#0000cd', category: 'Blue' },
  { name: 'Medium slate blue', hex: '#7b68ee', category: 'Blue' },
  { name: 'Midnight blue', hex: '#191970', category: 'Blue' },
  { name: 'Navy blue', hex: '#000080', category: 'Blue' },
  { name: 'Ocean blue', hex: '#4f6d7a', category: 'Blue' },
  { name: 'Oxford blue', hex: '#002147', category: 'Blue' },
  { name: 'Palatinate blue', hex: '#273be2', category: 'Blue' },
  { name: 'Pastel blue', hex: '#aec6cf', category: 'Blue' },
  { name: 'Periwinkle', hex: '#ccccff', category: 'Blue' },
  { name: 'Persian blue', hex: '#1c39bb', category: 'Blue' },
  { name: 'Phthalo blue', hex: '#000f89', category: 'Blue' },
  { name: 'Powder blue', hex: '#b0e0e6', category: 'Blue' },
  { name: 'Prussian blue', hex: '#003153', category: 'Blue' },
  { name: 'Royal blue', hex: '#4169e1', category: 'Blue' },
  { name: 'Sapphire', hex: '#0f52ba', category: 'Blue' },
  { name: 'Sky blue', hex: '#87ceeb', category: 'Blue' },
  { name: 'Slate blue', hex: '#6a5acd', category: 'Blue' },
  { name: 'Space cadet', hex: '#1d2951', category: 'Blue' },
  { name: 'Steel blue', hex: '#4682b4', category: 'Blue' },
  { name: 'Teal blue', hex: '#367588', category: 'Blue' },
  { name: 'True blue', hex: '#0073e6', category: 'Blue' },
  { name: 'Tufts blue', hex: '#417dc1', category: 'Blue' },
  { name: 'Turquoise blue', hex: '#00ffef', category: 'Blue' },
  { name: 'Ultramarine', hex: '#120a8f', category: 'Blue' },
  { name: 'United Nations blue', hex: '#5b92e5', category: 'Blue' },
  { name: 'Vivid blue', hex: '#0080ff', category: 'Blue' },
  { name: 'Yale blue', hex: '#0f4d92', category: 'Blue' },
  { name: 'Zaffre', hex: '#0014a8', category: 'Blue' },
  { name: 'Aqua', hex: '#00ffff', category: 'Blue' },
  { name: 'Aquamarine', hex: '#7fffd4', category: 'Blue' },
  { name: 'Cerulean frost', hex: '#6d9bc3', category: 'Blue' },
  { name: 'Cornflower', hex: '#9aceeb', category: 'Blue' },
  { name: 'Electric indigo', hex: '#6f00ff', category: 'Blue' },
  { name: 'Honolulu blue', hex: '#006db0', category: 'Blue' },
  { name: 'Iceberg', hex: '#71a6d2', category: 'Blue' },
  { name: 'Indigo dye', hex: '#00416a', category: 'Blue' },
  { name: 'Liberty', hex: '#545aa7', category: 'Blue' },
  { name: 'Medium electric blue', hex: '#035096', category: 'Blue' },
  { name: 'Moonstone blue', hex: '#73a9c2', category: 'Blue' },
  { name: 'Non-photo blue', hex: '#a4dded', category: 'Blue' },
  { name: 'Picton blue', hex: '#45b1e8', category: 'Blue' },
  { name: 'Resolution blue', hex: '#002387', category: 'Blue' },
  { name: 'Star command blue', hex: '#007bb8', category: 'Blue' },
  { name: 'Tiffany blue', hex: '#0abab5', category: 'Blue' },
  // Turquoise colors (expanded to 35 colors)
  { name: 'Aqua', hex: '#00ffff', category: 'Turquoise' },
  { name: 'Aquamarine', hex: '#7fffd4', category: 'Turquoise' },
  { name: 'Bright turquoise', hex: '#08e8de', category: 'Turquoise' },
  { name: 'Cadet blue', hex: '#5f9ea0', category: 'Turquoise' },
  { name: 'Celeste', hex: '#b2ffff', category: 'Turquoise' },
  { name: 'Cyan', hex: '#00ffff', category: 'Turquoise' },
  { name: 'Dark cyan', hex: '#008b8b', category: 'Turquoise' },
  { name: 'Dark turquoise', hex: '#00ced1', category: 'Turquoise' },
  { name: 'Electric blue', hex: '#7df9ff', category: 'Turquoise' },
  { name: 'Light blue', hex: '#add8e6', category: 'Turquoise' },
  { name: 'Light cyan', hex: '#e0ffff', category: 'Turquoise' },
  { name: 'Light sea green', hex: '#20b2aa', category: 'Turquoise' },
  { name: 'Medium aquamarine', hex: '#66ddaa', category: 'Turquoise' },
  { name: 'Medium turquoise', hex: '#48d1cc', category: 'Turquoise' },
  { name: 'Pale turquoise', hex: '#afeeee', category: 'Turquoise' },
  { name: 'Powder blue', hex: '#b0e0e6', category: 'Turquoise' },
  { name: 'Robin egg blue', hex: '#00cccc', category: 'Turquoise' },
  { name: 'Sea green', hex: '#2e8b57', category: 'Turquoise' },
  { name: 'Teal', hex: '#008080', category: 'Turquoise' },
  { name: 'Tiffany blue', hex: '#0abab5', category: 'Turquoise' },
  { name: 'Turquoise', hex: '#40e0d0', category: 'Turquoise' },
  { name: 'Turquoise blue', hex: '#00ffef', category: 'Turquoise' },
  { name: 'Turquoise green', hex: '#a0d6b4', category: 'Turquoise' },
  { name: 'Verdigris', hex: '#43b3ae', category: 'Turquoise' },
  { name: 'Viridian', hex: '#40826d', category: 'Turquoise' },
  { name: 'Waterspout', hex: '#a4f4f9', category: 'Turquoise' },
  { name: 'Blue green', hex: '#0d98ba', category: 'Turquoise' },
  { name: 'Caribbean green', hex: '#00cc99', category: 'Turquoise' },
  { name: 'Cerulean', hex: '#007ba7', category: 'Turquoise' },
  { name: 'Dark sea green', hex: '#8fbc8f', category: 'Turquoise' },
  { name: 'Jade', hex: '#00a86b', category: 'Turquoise' },
  { name: 'Mint', hex: '#3eb489', category: 'Turquoise' },
  { name: 'Persian green', hex: '#00a693', category: 'Turquoise' },
  { name: 'Pine green', hex: '#01796f', category: 'Turquoise' },
  { name: 'Steel teal', hex: '#5f8a8b', category: 'Turquoise' },

  // Violet/Purple colors (expanded to 50 colors)
  { name: 'African violet', hex: '#b284be', category: 'Violet' },
  { name: 'Amethyst', hex: '#9966cc', category: 'Violet' },
  { name: 'Blue violet', hex: '#8a2be2', category: 'Violet' },
  { name: 'Byzantium', hex: '#702963', category: 'Violet' },
  { name: 'Dark magenta', hex: '#8b008b', category: 'Violet' },
  { name: 'Dark orchid', hex: '#9932cc', category: 'Violet' },
  { name: 'Dark purple', hex: '#301934', category: 'Violet' },
  { name: 'Dark slate blue', hex: '#483d8b', category: 'Violet' },
  { name: 'Dark violet', hex: '#9400d3', category: 'Violet' },
  { name: 'Deep lilac', hex: '#9955bb', category: 'Violet' },
  { name: 'Deep magenta', hex: '#cc00cc', category: 'Violet' },
  { name: 'Electric purple', hex: '#bf00ff', category: 'Violet' },
  { name: 'Eggplant', hex: '#614051', category: 'Violet' },
  { name: 'French lilac', hex: '#86608e', category: 'Violet' },
  { name: 'Fuchsia', hex: '#ff00ff', category: 'Violet' },
  { name: 'Grape', hex: '#6f2da8', category: 'Violet' },
  { name: 'Heliotrope', hex: '#df73ff', category: 'Violet' },
  { name: 'Imperial purple', hex: '#602f6b', category: 'Violet' },
  { name: 'Indigo', hex: '#4b0082', category: 'Violet' },
  { name: 'Lavender', hex: '#e6e6fa', category: 'Violet' },
  { name: 'Lavender blush', hex: '#fff0f5', category: 'Violet' },
  { name: 'Lavender purple', hex: '#967bb6', category: 'Violet' },
  { name: 'Light purple', hex: '#b19cd9', category: 'Violet' },
  { name: 'Lilac', hex: '#c8a2c8', category: 'Violet' },
  { name: 'Magenta', hex: '#ff00ff', category: 'Violet' },
  { name: 'Mauve', hex: '#e0b0ff', category: 'Violet' },
  { name: 'Medium orchid', hex: '#ba55d3', category: 'Violet' },
  { name: 'Medium purple', hex: '#9370db', category: 'Violet' },
  { name: 'Medium slate blue', hex: '#7b68ee', category: 'Violet' },
  { name: 'Medium violet red', hex: '#c71585', category: 'Violet' },
  { name: 'Mulberry', hex: '#c54b8c', category: 'Violet' },
  { name: 'Orchid', hex: '#da70d6', category: 'Violet' },
  { name: 'Pale violet red', hex: '#db7093', category: 'Violet' },
  { name: 'Pansy purple', hex: '#78184a', category: 'Violet' },
  { name: 'Pastel purple', hex: '#b39eb5', category: 'Violet' },
  { name: 'Periwinkle', hex: '#ccccff', category: 'Violet' },
  { name: 'Persian indigo', hex: '#32127a', category: 'Violet' },
  { name: 'Plum', hex: '#dda0dd', category: 'Violet' },
  { name: 'Purple', hex: '#800080', category: 'Violet' },
  { name: 'Purple heart', hex: '#69359c', category: 'Violet' },
  { name: 'Rebecca purple', hex: '#663399', category: 'Violet' },
  { name: 'Red violet', hex: '#c71585', category: 'Violet' },
  { name: 'Royal purple', hex: '#7851a9', category: 'Violet' },
  { name: 'Slate blue', hex: '#6a5acd', category: 'Violet' },
  { name: 'Thistle', hex: '#d8bfd8', category: 'Violet' },
  { name: 'Tyrian purple', hex: '#66023c', category: 'Violet' },
  { name: 'Violet', hex: '#ee82ee', category: 'Violet' },
  { name: 'Violet red', hex: '#f75394', category: 'Violet' },
  { name: 'Wisteria', hex: '#c9a0dc', category: 'Violet' },
  { name: 'Wood violet', hex: '#674c47', category: 'Violet' },
  { name: 'Xanadu', hex: '#738678', category: 'Violet' },

  // Pink colors (expanded to 45 colors)
  { name: 'Amaranth pink', hex: '#f19cbb', category: 'Pink' },
  { name: 'Ballet slipper', hex: '#ffeef5', category: 'Pink' },
  { name: 'Blush', hex: '#de5d83', category: 'Pink' },
  { name: 'Brink pink', hex: '#fb607f', category: 'Pink' },
  { name: 'Bubble gum', hex: '#ffc1cc', category: 'Pink' },
  { name: 'Cameo pink', hex: '#efbbcc', category: 'Pink' },
  { name: 'Carnation pink', hex: '#ffa6c9', category: 'Pink' },
  { name: 'Cerise pink', hex: '#ec3b83', category: 'Pink' },
  { name: 'Cherry blossom pink', hex: '#ffb7c5', category: 'Pink' },
  { name: 'China pink', hex: '#de6fa1', category: 'Pink' },
  { name: 'Cotton candy', hex: '#ffbcd9', category: 'Pink' },
  { name: 'Deep pink', hex: '#ff1493', category: 'Pink' },
  { name: 'Dusty pink', hex: '#dc9fb4', category: 'Pink' },
  { name: 'Flamingo pink', hex: '#fc8eac', category: 'Pink' },
  { name: 'French pink', hex: '#fd6c9e', category: 'Pink' },
  { name: 'French rose', hex: '#f64a8a', category: 'Pink' },
  { name: 'Fuchsia pink', hex: '#ff77ff', category: 'Pink' },
  { name: 'Hot pink', hex: '#ff69b4', category: 'Pink' },
  { name: 'Light pink', hex: '#ffb6c1', category: 'Pink' },
  { name: 'Magenta pink', hex: '#cc338b', category: 'Pink' },
  { name: 'Magenta rose', hex: '#ff00af', category: 'Pink' },
  { name: 'Misty rose', hex: '#ffe4e1', category: 'Pink' },
  { name: 'Mauvelous', hex: '#ef98aa', category: 'Pink' },
  { name: 'Orchid pink', hex: '#f2bdcd', category: 'Pink' },
  { name: 'Pale pink', hex: '#fadadd', category: 'Pink' },
  { name: 'Pastel pink', hex: '#dea5a4', category: 'Pink' },
  { name: 'Peach pink', hex: '#fadfad', category: 'Pink' },
  { name: 'Persian pink', hex: '#f77fbe', category: 'Pink' },
  { name: 'Pink', hex: '#ffc0cb', category: 'Pink' },
  { name: 'Pink flamingo', hex: '#fc74fd', category: 'Pink' },
  { name: 'Pink pearl', hex: '#e7accf', category: 'Pink' },
  { name: 'Pink sherbet', hex: '#f78fa7', category: 'Pink' },
  { name: 'Powder pink', hex: '#ffb3ba', category: 'Pink' },
  { name: 'Princess pink', hex: '#ffc6d2', category: 'Pink' },
  { name: 'Rose', hex: '#ff007f', category: 'Pink' },
  { name: 'Rose pink', hex: '#ff66cc', category: 'Pink' },
  { name: 'Rosy brown', hex: '#bc8f8f', category: 'Pink' },
  { name: 'Ruby pink', hex: '#e0115f', category: 'Pink' },
  { name: 'Salmon pink', hex: '#ff91a4', category: 'Pink' },
  { name: 'Shocking pink', hex: '#fc0fc0', category: 'Pink' },
  { name: 'Strawberry', hex: '#fc5a8d', category: 'Pink' },
  { name: 'Thulian pink', hex: '#de6fa1', category: 'Pink' },
  { name: 'Tickle me pink', hex: '#fc89ac', category: 'Pink' },
  { name: 'Ultra pink', hex: '#ff6fff', category: 'Pink' },
  { name: 'Watermelon', hex: '#ff7f7f', category: 'Pink' },

  // Brown colors (expanded to 50 colors)
  { name: 'Almond', hex: '#efdecd', category: 'Brown' },
  { name: 'Antique brass', hex: '#cd7f32', category: 'Brown' },
  { name: 'Auburn', hex: '#a52a2a', category: 'Brown' },
  { name: 'Beaver', hex: '#9f8170', category: 'Brown' },
  { name: 'Beige', hex: '#f5f5dc', category: 'Brown' },
  { name: 'Bisque', hex: '#ffe4c4', category: 'Brown' },
  { name: 'Bole', hex: '#79443b', category: 'Brown' },
  { name: 'Bronze', hex: '#cd7f32', category: 'Brown' },
  { name: 'Brown', hex: '#964b00', category: 'Brown' },
  { name: 'Buff', hex: '#f0dc82', category: 'Brown' },
  { name: 'Burly wood', hex: '#deb887', category: 'Brown' },
  { name: 'Burnt sienna', hex: '#e97451', category: 'Brown' },
  { name: 'Burnt umber', hex: '#8a3324', category: 'Brown' },
  { name: 'Cafe au lait', hex: '#a67b5b', category: 'Brown' },
  { name: 'Camel', hex: '#c19a6b', category: 'Brown' },
  { name: 'Caput mortuum', hex: '#592720', category: 'Brown' },
  { name: 'Chamoisee', hex: '#a0785a', category: 'Brown' },
  { name: 'Chestnut', hex: '#954535', category: 'Brown' },
  { name: 'Chocolate', hex: '#d2691e', category: 'Brown' },
  { name: 'Cinnamon', hex: '#d2691e', category: 'Brown' },
  { name: 'Coconut', hex: '#965a3e', category: 'Brown' },
  { name: 'Coffee', hex: '#6f4e37', category: 'Brown' },
  { name: 'Cognac', hex: '#9a463d', category: 'Brown' },
  { name: 'Copper', hex: '#b87333', category: 'Brown' },
  { name: 'Dark brown', hex: '#654321', category: 'Brown' },
  { name: 'Desert sand', hex: '#edc9af', category: 'Brown' },
  { name: 'Dirt brown', hex: '#8b7355', category: 'Brown' },
  { name: 'Dun', hex: '#ddbf94', category: 'Brown' },
  { name: 'Ecru', hex: '#c2b280', category: 'Brown' },
  { name: 'Fallow', hex: '#c19a6b', category: 'Brown' },
  { name: 'Fawn', hex: '#e5aa70', category: 'Brown' },
  { name: 'Field drab', hex: '#6c541e', category: 'Brown' },
  { name: 'Fulvous', hex: '#e48400', category: 'Brown' },
  { name: 'Ginger', hex: '#b06500', category: 'Brown' },
  { name: 'Hazel', hex: '#8e7618', category: 'Brown' },
  { name: 'Khaki', hex: '#f0e68c', category: 'Brown' },
  { name: 'Light brown', hex: '#b5651d', category: 'Brown' },
  { name: 'Liver', hex: '#534b4f', category: 'Brown' },
  { name: 'Mahogany', hex: '#c04000', category: 'Brown' },
  { name: 'Mocha', hex: '#967117', category: 'Brown' },
  { name: 'Moccasin', hex: '#ffe4b5', category: 'Brown' },
  { name: 'Ochre', hex: '#cc7722', category: 'Brown' },
  { name: 'Raw umber', hex: '#826644', category: 'Brown' },
  { name: 'Russet', hex: '#80461b', category: 'Brown' },
  { name: 'Rust', hex: '#b7410e', category: 'Brown' },
  { name: 'Saddle brown', hex: '#8b4513', category: 'Brown' },
  { name: 'Sepia', hex: '#704214', category: 'Brown' },
  { name: 'Sienna', hex: '#a0522d', category: 'Brown' },
  { name: 'Tan', hex: '#d2b48c', category: 'Brown' },
  { name: 'Umber', hex: '#635147', category: 'Brown' },

  // Gray colors (expanded to 35 colors)
  { name: 'Ash gray', hex: '#b2beb5', category: 'Gray' },
  { name: 'Battleship gray', hex: '#848482', category: 'Gray' },
  { name: 'Cadet gray', hex: '#91a3b0', category: 'Gray' },
  { name: 'Charcoal', hex: '#36454f', category: 'Gray' },
  { name: 'Cool gray', hex: '#8c92ac', category: 'Gray' },
  { name: 'Dark gray', hex: '#a9a9a9', category: 'Gray' },
  { name: 'Dark slate gray', hex: '#2f4f4f', category: 'Gray' },
  { name: 'Davy gray', hex: '#555555', category: 'Gray' },
  { name: 'Dim gray', hex: '#696969', category: 'Gray' },
  { name: 'Dove gray', hex: '#6d6c74', category: 'Gray' },
  { name: 'Gainsboro', hex: '#dcdcdc', category: 'Gray' },
  { name: 'Gray', hex: '#808080', category: 'Gray' },
  { name: 'Gray blue', hex: '#8c92ac', category: 'Gray' },
  { name: 'Gunmetal gray', hex: '#818589', category: 'Gray' },
  { name: 'Light gray', hex: '#d3d3d3', category: 'Gray' },
  { name: 'Light slate gray', hex: '#778899', category: 'Gray' },
  { name: 'Medium gray', hex: '#bebebe', category: 'Gray' },
  { name: 'Nickel', hex: '#727472', category: 'Gray' },
  { name: 'Payne gray', hex: '#536878', category: 'Gray' },
  { name: 'Pewter', hex: '#96a8a1', category: 'Gray' },
  { name: 'Platinum', hex: '#e5e4e2', category: 'Gray' },
  { name: 'Quick silver', hex: '#a6a6a6', category: 'Gray' },
  { name: 'Rosybrown', hex: '#bc8f8f', category: 'Gray' },
  { name: 'Silver', hex: '#c0c0c0', category: 'Gray' },
  { name: 'Silver chalice', hex: '#acacac', category: 'Gray' },
  { name: 'Slate gray', hex: '#708090', category: 'Gray' },
  { name: 'Smoke', hex: '#738276', category: 'Gray' },
  { name: 'Spanish gray', hex: '#989898', category: 'Gray' },
  { name: 'Taupe gray', hex: '#8b8589', category: 'Gray' },
  { name: 'Timberwolf', hex: '#dbd7d2', category: 'Gray' },
  { name: 'Trolley gray', hex: '#808080', category: 'Gray' },
  { name: 'Warm gray', hex: '#808069', category: 'Gray' },
  { name: 'White smoke', hex: '#f5f5f5', category: 'Gray' },
  { name: 'X11 gray', hex: '#bebebe', category: 'Gray' },
  { name: 'Xanadu', hex: '#738678', category: 'Gray' },

  // Black colors (expanded to 12 colors)
  { name: 'Black', hex: '#000000', category: 'Black' },
  { name: 'Black bean', hex: '#3d0c02', category: 'Black' },
  { name: 'Charcoal', hex: '#36454f', category: 'Black' },
  { name: 'Dark charcoal', hex: '#333333', category: 'Black' },
  { name: 'Ebony', hex: '#555d50', category: 'Black' },
  { name: 'Jet black', hex: '#0a0a0a', category: 'Black' },
  { name: 'Licorice', hex: '#1a1110', category: 'Black' },
  { name: 'Midnight', hex: '#2f1b14', category: 'Black' },
  { name: 'Night', hex: '#0c090a', category: 'Black' },
  { name: 'Obsidian', hex: '#3c4142', category: 'Black' },
  { name: 'Onyx', hex: '#353839', category: 'Black' },
  { name: 'Rich black', hex: '#010b13', category: 'Black' },

  // White colors (expanded to 15 colors)
  { name: 'Antique white', hex: '#faebd7', category: 'White' },
  { name: 'Beige', hex: '#f5f5dc', category: 'White' },
  { name: 'Blanched almond', hex: '#ffebcd', category: 'White' },
  { name: 'Cornsilk', hex: '#fff8dc', category: 'White' },
  { name: 'Cream', hex: '#fffdd0', category: 'White' },
  { name: 'Eggshell', hex: '#f0ead6', category: 'White' },
  { name: 'Floral white', hex: '#fffaf0', category: 'White' },
  { name: 'Ghost white', hex: '#f8f8ff', category: 'White' },
  { name: 'Ivory', hex: '#fffff0', category: 'White' },
  { name: 'Linen', hex: '#faf0e6', category: 'White' },
  { name: 'Old lace', hex: '#fdf5e6', category: 'White' },
  { name: 'Off-white', hex: '#faf0e6', category: 'White' },
  { name: 'Pearl', hex: '#eae0c8', category: 'White' },
  { name: 'Snow', hex: '#fffafa', category: 'White' },
  { name: 'White', hex: '#ffffff', category: 'White' }
];