import { ColorItem } from '../colorData';

export const blueColors: ColorItem[] = [
  { name: 'Air Force blue', hex: '#5d8aa8', category: 'Blue' },
  { name: 'Alice blue', hex: '#f0f8ff', category: 'Blue' },
  { name: 'Azure', hex: '#007fff', category: 'Blue' },
  { name: 'Baby blue', hex: '#89cff0', category: 'Blue' },
  { name: 'Blue', hex: '#0000ff', category: 'Blue' },
  { name: 'Blue bell', hex: '#a2a2d0', category: 'Blue' },
  { name: 'Blue gray', hex: '#6699cc', category: 'Blue' },
  { name: 'Blue sapphire', hex: '#126180', category: 'Blue' },
  { name: 'Blueberry', hex: '#4f86f7', category: 'Blue' },
  { name: 'Bondi blue', hex: '#0095b6', category: 'Blue' },
  { name: 'Brandeis blue', hex: '#0070ff', category: 'Blue' },
  { name: 'Cambridge blue', hex: '#a3c1ad', category: 'Blue' },
  { name: 'Cadet blue', hex: '#5f9ea0', category: 'Blue' },
  { name: 'Capri', hex: '#00bfff', category: 'Blue' },
  { name: 'Carolina blue', hex: '#56a0d3', category: 'Blue' },
  { name: 'Celestial blue', hex: '#4997d0', category: 'Blue' },
  { name: 'Cerulean', hex: '#007ba7', category: 'Blue' },
  { name: 'Cerulean blue', hex: '#2a52be', category: 'Blue' },
  { name: 'Cobalt blue', hex: '#0047ab', category: 'Blue' },
  { name: 'Columbia blue', hex: '#9bddff', category: 'Blue' },
  { name: 'Cornflower blue', hex: '#6495ed', category: 'Blue' },
  { name: 'Crystal blue', hex: '#68a0b0', category: 'Blue' },
  { name: 'Cyan', hex: '#00ffff', category: 'Blue' },
  { name: 'Dark blue', hex: '#00008b', category: 'Blue' },
  { name: 'Dark cyan', hex: '#008b8b', category: 'Blue' },
  { name: 'Dark powder blue', hex: '#003399', category: 'Blue' },
  { name: 'Dark slate blue', hex: '#483d8b', category: 'Blue' },
  { name: 'Dark turquoise', hex: '#00ced1', category: 'Blue' },
  { name: 'Deep blue', hex: '#040f75', category: 'Blue' },
  { name: 'Deep sky blue', hex: '#00bfff', category: 'Blue' },
  { name: 'Denim', hex: '#1560bd', category: 'Blue' },
  { name: 'Dodger blue', hex: '#1e90ff', category: 'Blue' },
  { name: 'Duke blue', hex: '#00009c', category: 'Blue' },
  { name: 'Egyptian blue', hex: '#1034a6', category: 'Blue' },
  { name: 'Electric blue', hex: '#7df9ff', category: 'Blue' },
  { name: 'French blue', hex: '#0072bb', category: 'Blue' },
  { name: 'Glaucous', hex: '#6082b6', category: 'Blue' },
  { name: 'Han blue', hex: '#446ccf', category: 'Blue' },
  { name: 'Ice blue', hex: '#99d9ea', category: 'Blue' },
  { name: 'International Klein Blue', hex: '#002fa7', category: 'Blue' },
  { name: 'Iris', hex: '#5a4fcf', category: 'Blue' },
  { name: 'Light blue', hex: '#add8e6', category: 'Blue' },
  { name: 'Light cyan', hex: '#e0ffff', category: 'Blue' },
  { name: 'Light sky blue', hex: '#87cefa', category: 'Blue' },
  { name: 'Light slate blue', hex: '#8470ff', category: 'Blue' },
  { name: 'Light steel blue', hex: '#b0c4de', category: 'Blue' },
  { name: 'Lapis lazuli', hex: '#26619c', category: 'Blue' },
  { name: 'Maya blue', hex: '#73c2fb', category: 'Blue' },
  { name: 'Medium blue', hex: '#0000cd', category: 'Blue' },
  { name: 'Medium slate blue', hex: '#7b68ee', category: 'Blue' },
  { name: 'Midnight blue', hex: '#191970', category: 'Blue' },
  { name: 'Navy blue', hex: '#000080', category: 'Blue' },
  { name: 'Ocean blue', hex: '#4f6d7a', category: 'Blue' },
  { name: 'Oxford blue', hex: '#002147', category: 'Blue' },
  { name: 'Palatinate blue', hex: '#273be2', category: 'Blue' },
  { name: 'Pastel blue', hex: '#aec6cf', category: 'Blue' },
  { name: 'Periwinkle', hex: '#ccccff', category: 'Blue' },
  { name: 'Persian blue', hex: '#1c39bb', category: 'Blue' },
  { name: 'Phthalo blue', hex: '#000f89', category: 'Blue' },
  { name: 'Powder blue', hex: '#b0e0e6', category: 'Blue' },
  { name: 'Prussian blue', hex: '#003153', category: 'Blue' },
  { name: 'Royal blue', hex: '#4169e1', category: 'Blue' },
  { name: 'Sapphire', hex: '#0f52ba', category: 'Blue' },
  { name: 'Sky blue', hex: '#87ceeb', category: 'Blue' },
  { name: 'Slate blue', hex: '#6a5acd', category: 'Blue' },
  { name: 'Space cadet', hex: '#1d2951', category: 'Blue' },
  { name: 'Steel blue', hex: '#4682b4', category: 'Blue' },
  { name: 'Teal blue', hex: '#367588', category: 'Blue' },
  { name: 'True blue', hex: '#0073e6', category: 'Blue' },
  { name: 'Tufts blue', hex: '#417dc1', category: 'Blue' },
  { name: 'Turquoise blue', hex: '#00ffef', category: 'Blue' },
  { name: 'Ultramarine', hex: '#120a8f', category: 'Blue' },
  { name: 'United Nations blue', hex: '#5b92e5', category: 'Blue' },
  { name: 'Vivid blue', hex: '#0080ff', category: 'Blue' },
  { name: 'Yale blue', hex: '#0f4d92', category: 'Blue' },
  { name: 'Zaffre', hex: '#0014a8', category: 'Blue' },
  { name: 'Aqua', hex: '#00ffff', category: 'Blue' },
  { name: 'Aquamarine', hex: '#7fffd4', category: 'Blue' },
  { name: 'Cerulean frost', hex: '#6d9bc3', category: 'Blue' },
  { name: 'Cornflower', hex: '#9aceeb', category: 'Blue' },
  { name: 'Electric indigo', hex: '#6f00ff', category: 'Blue' },
  { name: 'Honolulu blue', hex: '#006db0', category: 'Blue' },
  { name: 'Iceberg', hex: '#71a6d2', category: 'Blue' },
  { name: 'Indigo dye', hex: '#00416a', category: 'Blue' },
  { name: 'Liberty', hex: '#545aa7', category: 'Blue' },
  { name: 'Medium electric blue', hex: '#035096', category: 'Blue' },
  { name: 'Moonstone blue', hex: '#73a9c2', category: 'Blue' },
  { name: 'Non-photo blue', hex: '#a4dded', category: 'Blue' },
  { name: 'Picton blue', hex: '#45b1e8', category: 'Blue' },
  { name: 'Resolution blue', hex: '#002387', category: 'Blue' },
  { name: 'Star command blue', hex: '#007bb8', category: 'Blue' },
  { name: 'Tiffany blue', hex: '#0abab5', category: 'Blue' }
];