import { ColorItem } from '../colorData';

export const brownColors: ColorItem[] = [
  { name: 'Almond', hex: '#efdecd', category: 'Brown' },
  { name: 'Antique brass', hex: '#cd7f32', category: 'Brown' },
  { name: 'Auburn', hex: '#a52a2a', category: 'Brown' },
  { name: 'Beaver', hex: '#9f8170', category: 'Brown' },
  { name: 'Beige', hex: '#f5f5dc', category: 'Brown' },
  { name: 'Bisque', hex: '#ffe4c4', category: 'Brown' },
  { name: 'Bole', hex: '#79443b', category: 'Brown' },
  { name: 'Bronze', hex: '#cd7f32', category: 'Brown' },
  { name: 'Brown', hex: '#964b00', category: 'Brown' },
  { name: 'Buff', hex: '#f0dc82', category: 'Brown' },
  { name: 'Burly wood', hex: '#deb887', category: 'Brown' },
  { name: 'Burnt sienna', hex: '#e97451', category: 'Brown' },
  { name: 'Burnt umber', hex: '#8a3324', category: 'Brown' },
  { name: 'Cafe au lait', hex: '#a67b5b', category: 'Brown' },
  { name: 'Camel', hex: '#c19a6b', category: 'Brown' },
  { name: 'Caput mortuum', hex: '#592720', category: 'Brown' },
  { name: 'Chamoisee', hex: '#a0785a', category: 'Brown' },
  { name: 'Chestnut', hex: '#954535', category: 'Brown' },
  { name: 'Chocolate', hex: '#d2691e', category: 'Brown' },
  { name: 'Cinnamon', hex: '#d2691e', category: 'Brown' },
  { name: 'Coconut', hex: '#965a3e', category: 'Brown' },
  { name: 'Coffee', hex: '#6f4e37', category: 'Brown' },
  { name: 'Cognac', hex: '#9a463d', category: 'Brown' },
  { name: 'Copper', hex: '#b87333', category: 'Brown' },
  { name: 'Dark brown', hex: '#654321', category: 'Brown' },
  { name: 'Desert sand', hex: '#edc9af', category: 'Brown' },
  { name: 'Dirt brown', hex: '#8b7355', category: 'Brown' },
  { name: 'Dun', hex: '#ddbf94', category: 'Brown' },
  { name: 'Ecru', hex: '#c2b280', category: 'Brown' },
  { name: 'Fallow', hex: '#c19a6b', category: 'Brown' },
  { name: 'Fawn', hex: '#e5aa70', category: 'Brown' },
  { name: 'Field drab', hex: '#6c541e', category: 'Brown' },
  { name: 'Fulvous', hex: '#e48400', category: 'Brown' },
  { name: 'Ginger', hex: '#b06500', category: 'Brown' },
  { name: 'Hazel', hex: '#8e7618', category: 'Brown' },
  { name: 'Khaki', hex: '#f0e68c', category: 'Brown' },
  { name: 'Light brown', hex: '#b5651d', category: 'Brown' },
  { name: 'Liver', hex: '#534b4f', category: 'Brown' },
  { name: 'Mahogany', hex: '#c04000', category: 'Brown' },
  { name: 'Mocha', hex: '#967117', category: 'Brown' },
  { name: 'Moccasin', hex: '#ffe4b5', category: 'Brown' },
  { name: 'Ochre', hex: '#cc7722', category: 'Brown' },
  { name: 'Raw umber', hex: '#826644', category: 'Brown' },
  { name: 'Russet', hex: '#80461b', category: 'Brown' },
  { name: 'Rust', hex: '#b7410e', category: 'Brown' },
  { name: 'Saddle brown', hex: '#8b4513', category: 'Brown' },
  { name: 'Sepia', hex: '#704214', category: 'Brown' },
  { name: 'Sienna', hex: '#a0522d', category: 'Brown' },
  { name: 'Tan', hex: '#d2b48c', category: 'Brown' },
  { name: 'Umber', hex: '#635147', category: 'Brown' }
];