import { ColorItem } from '../colorData';

export const grayColors: ColorItem[] = [
  { name: 'Ash gray', hex: '#b2beb5', category: 'Gray' },
  { name: 'Battleship gray', hex: '#848482', category: 'Gray' },
  { name: 'Cadet gray', hex: '#91a3b0', category: 'Gray' },
  { name: 'Charcoal', hex: '#36454f', category: 'Gray' },
  { name: 'Cool gray', hex: '#8c92ac', category: 'Gray' },
  { name: 'Dark gray', hex: '#a9a9a9', category: 'Gray' },
  { name: 'Dark slate gray', hex: '#2f4f4f', category: 'Gray' },
  { name: 'Davy gray', hex: '#555555', category: 'Gray' },
  { name: 'Dim gray', hex: '#696969', category: 'Gray' },
  { name: 'Dove gray', hex: '#6d6c74', category: 'Gray' },
  { name: 'Gainsboro', hex: '#dcdcdc', category: 'Gray' },
  { name: 'Gray', hex: '#808080', category: 'Gray' },
  { name: 'Gray blue', hex: '#8c92ac', category: 'Gray' },
  { name: 'Gunmetal gray', hex: '#818589', category: 'Gray' },
  { name: 'Light gray', hex: '#d3d3d3', category: 'Gray' },
  { name: 'Light slate gray', hex: '#778899', category: 'Gray' },
  { name: 'Medium gray', hex: '#bebebe', category: 'Gray' },
  { name: 'Nickel', hex: '#727472', category: 'Gray' },
  { name: 'Payne gray', hex: '#536878', category: 'Gray' },
  { name: 'Pewter', hex: '#96a8a1', category: 'Gray' },
  { name: 'Platinum', hex: '#e5e4e2', category: 'Gray' },
  { name: 'Quick silver', hex: '#a6a6a6', category: 'Gray' },
  { name: 'Rosybrown', hex: '#bc8f8f', category: 'Gray' },
  { name: 'Silver', hex: '#c0c0c0', category: 'Gray' },
  { name: 'Silver chalice', hex: '#acacac', category: 'Gray' },
  { name: 'Slate gray', hex: '#708090', category: 'Gray' },
  { name: 'Smoke', hex: '#738276', category: 'Gray' },
  { name: 'Spanish gray', hex: '#989898', category: 'Gray' },
  { name: 'Taupe gray', hex: '#8b8589', category: 'Gray' },
  { name: 'Timberwolf', hex: '#dbd7d2', category: 'Gray' },
  { name: 'Trolley gray', hex: '#808080', category: 'Gray' },
  { name: 'Warm gray', hex: '#808069', category: 'Gray' },
  { name: 'White smoke', hex: '#f5f5f5', category: 'Gray' },
  { name: 'X11 gray', hex: '#bebebe', category: 'Gray' },
  { name: 'Xanadu', hex: '#738678', category: 'Gray' }
];