import { ColorItem } from '../colorData';

export const greenColors: ColorItem[] = [
  { name: 'Absinthe', hex: '#74c365', category: 'Green' },
  { name: 'Acid green', hex: '#b0bf1a', category: 'Green' },
  { name: 'Algae green', hex: '#64e986', category: 'Green' },
  { name: 'Amazon', hex: '#3b7a57', category: 'Green' },
  { name: 'Android green', hex: '#a4c639', category: 'Green' },
  { name: 'Apple green', hex: '#8db600', category: 'Green' },
  { name: 'Army green', hex: '#4b5320', category: 'Green' },
  { name: 'Artichoke', hex: '#8f9779', category: 'Green' },
  { name: 'Asparagus', hex: '#87a96b', category: 'Green' },
  { name: 'Avocado', hex: '#568203', category: 'Green' },
  { name: 'Bamboo', hex: '#c7cc9a', category: 'Green' },
  { name: 'Basil', hex: '#8a9a5b', category: 'Green' },
  { name: 'Bottle green', hex: '#006a4e', category: 'Green' },
  { name: 'British racing green', hex: '#004225', category: 'Green' },
  { name: 'Brunswick green', hex: '#1b4332', category: 'Green' },
  { name: 'Cadmium green', hex: '#006b3c', category: 'Green' },
  { name: 'Cambridge blue', hex: '#a3c1ad', category: 'Green' },
  { name: 'Celadon', hex: '#ace1af', category: 'Green' },
  { name: 'Chartreuse', hex: '#7fff00', category: 'Green' },
  { name: 'Chartreuse green', hex: '#7fff00', category: 'Green' },
  { name: 'Chrome green', hex: '#00573f', category: 'Green' },
  { name: 'Clover', hex: '#3ea055', category: 'Green' },
  { name: 'Conifer', hex: '#acdd4d', category: 'Green' },
  { name: 'Dartmouth green', hex: '#00703c', category: 'Green' },
  { name: 'Dark green', hex: '#006400', category: 'Green' },
  { name: 'Dark olive green', hex: '#556b2f', category: 'Green' },
  { name: 'Dark pastel green', hex: '#03c03c', category: 'Green' },
  { name: 'Dark sea green', hex: '#8fbc8f', category: 'Green' },
  { name: 'Electric green', hex: '#00ff00', category: 'Green' },
  { name: 'Emerald', hex: '#50c878', category: 'Green' },
  { name: 'Eucalyptus', hex: '#44d7a8', category: 'Green' },
  { name: 'Fern green', hex: '#4f7942', category: 'Green' },
  { name: 'Forest green', hex: '#228b22', category: 'Green' },
  { name: 'Go green', hex: '#00ab66', category: 'Green' },
  { name: 'Grass green', hex: '#7cfc00', category: 'Green' },
  { name: 'Green', hex: '#008000', category: 'Green' },
  { name: 'Green apple', hex: '#4cc417', category: 'Green' },
  { name: 'Green pea', hex: '#4dffb8', category: 'Green' },
  { name: 'Harlequin', hex: '#3fff00', category: 'Green' },
  { name: 'Hooker green', hex: '#49796b', category: 'Green' },
  { name: 'Hunter green', hex: '#355e3b', category: 'Green' },
  { name: 'India green', hex: '#138808', category: 'Green' },
  { name: 'Islamic green', hex: '#009000', category: 'Green' },
  { name: 'Jade', hex: '#00a86b', category: 'Green' },
  { name: 'Jungle green', hex: '#29ab87', category: 'Green' },
  { name: 'Kelly green', hex: '#4cbb17', category: 'Green' },
  { name: 'Kiwi', hex: '#8ee53f', category: 'Green' },
  { name: 'Lawn green', hex: '#7cfc00', category: 'Green' },
  { name: 'Leaf green', hex: '#5caa15', category: 'Green' },
  { name: 'Light green', hex: '#90ee90', category: 'Green' },
  { name: 'Light sea green', hex: '#20b2aa', category: 'Green' },
  { name: 'Lime', hex: '#00ff00', category: 'Green' },
  { name: 'Lime green', hex: '#32cd32', category: 'Green' },
  { name: 'Lincoln green', hex: '#195905', category: 'Green' },
  { name: 'Malachite', hex: '#0bda51', category: 'Green' },
  { name: 'May green', hex: '#4c9141', category: 'Green' },
  { name: 'Medium green', hex: '#00fa54', category: 'Green' },
  { name: 'Medium sea green', hex: '#3cb371', category: 'Green' },
  { name: 'Medium spring green', hex: '#00fa9a', category: 'Green' },
  { name: 'Military green', hex: '#667c3e', category: 'Green' },
  { name: 'Mint', hex: '#3eb489', category: 'Green' },
  { name: 'Mint cream', hex: '#f5fffa', category: 'Green' },
  { name: 'Mint green', hex: '#98fb98', category: 'Green' },
  { name: 'Moss green', hex: '#addfad', category: 'Green' },
  { name: 'Myrtle', hex: '#21421e', category: 'Green' },
  { name: 'Neon green', hex: '#39ff14', category: 'Green' },
  { name: 'Office green', hex: '#008000', category: 'Green' },
  { name: 'Olive', hex: '#808000', category: 'Green' },
  { name: 'Olive drab', hex: '#6b8e23', category: 'Green' },
  { name: 'Pakistan green', hex: '#006600', category: 'Green' },
  { name: 'Pale green', hex: '#98fb98', category: 'Green' },
  { name: 'Paris green', hex: '#50c878', category: 'Green' },
  { name: 'Pastel green', hex: '#77dd77', category: 'Green' },
  { name: 'Pea green', hex: '#8ebc00', category: 'Green' },
  { name: 'Persian green', hex: '#00a693', category: 'Green' },
  { name: 'Phthalo green', hex: '#123524', category: 'Green' },
  { name: 'Pine green', hex: '#01796f', category: 'Green' },
  { name: 'Pistachio', hex: '#93c572', category: 'Green' },
  { name: 'Racing green', hex: '#014421', category: 'Green' },
  { name: 'Reseda green', hex: '#6c7c32', category: 'Green' },
  { name: 'Rifle green', hex: '#414833', category: 'Green' },
  { name: 'Russian green', hex: '#679267', category: 'Green' },
  { name: 'Sage', hex: '#9caf88', category: 'Green' },
  { name: 'Sap green', hex: '#507d2a', category: 'Green' },
  { name: 'Sea green', hex: '#2e8b57', category: 'Green' },
  { name: 'Shamrock green', hex: '#009e60', category: 'Green' },
  { name: 'Spring bud', hex: '#a7fc00', category: 'Green' },
  { name: 'Spring green', hex: '#00ff7f', category: 'Green' },
  { name: 'Tea green', hex: '#d0f0c0', category: 'Green' },
  { name: 'Teal green', hex: '#00827f', category: 'Green' },
  { name: 'Turquoise green', hex: '#a0d6b4', category: 'Green' },
  { name: 'Viridian', hex: '#40826d', category: 'Green' },
  { name: 'Yellow green', hex: '#9acd32', category: 'Green' },
  { name: 'Zombie green', hex: '#54c571', category: 'Green' }
];