import { ColorItem } from '../colorData';

export const orangeColors: ColorItem[] = [
  { name: 'Amber', hex: '#ffbf00', category: 'Orange' },
  { name: 'Apricot', hex: '#fbceb1', category: 'Orange' },
  { name: 'Atomic tangerine', hex: '#ff9966', category: 'Orange' },
  { name: 'Bittersweet orange', hex: '#fe6f5e', category: 'Orange' },
  { name: 'Blaze orange', hex: '#ff6600', category: 'Orange' },
  { name: 'Burnt orange', hex: '#cc5500', category: 'Orange' },
  { name: 'Burnt sienna', hex: '#e97451', category: 'Orange' },
  { name: 'Cadmium orange', hex: '#ed872d', category: 'Orange' },
  { name: 'Carrot orange', hex: '#ed9121', category: 'Orange' },
  { name: 'Celosia orange', hex: '#ff4500', category: 'Orange' },
  { name: 'Chrome orange', hex: '#ffa000', category: 'Orange' },
  { name: 'Chrome yellow', hex: '#ffa700', category: 'Orange' },
  { name: 'Coral', hex: '#ff7f50', category: 'Orange' },
  { name: 'Dark orange', hex: '#ff8c00', category: 'Orange' },
  { name: 'Dark salmon', hex: '#e9967a', category: 'Orange' },
  { name: 'Deep carrot orange', hex: '#e9692c', category: 'Orange' },
  { name: 'Deep peach', hex: '#ffcba4', category: 'Orange' },
  { name: 'Dutch orange', hex: '#ff8200', category: 'Orange' },
  { name: 'Flame orange', hex: '#ff5100', category: 'Orange' },
  { name: 'Gamboge', hex: '#e49b0f', category: 'Orange' },
  { name: 'Georgia peach', hex: '#ffb347', category: 'Orange' },
  { name: 'Ginger', hex: '#b06500', category: 'Orange' },
  { name: 'Heat wave', hex: '#ff7a00', category: 'Orange' },
  { name: 'Honey orange', hex: '#ff8c69', category: 'Orange' },
  { name: 'International orange', hex: '#ff4f00', category: 'Orange' },
  { name: 'Kumquat', hex: '#ffa500', category: 'Orange' },
  { name: 'Light orange', hex: '#fed8b1', category: 'Orange' },
  { name: 'Light salmon', hex: '#ffa07a', category: 'Orange' },
  { name: 'Macaroni cheese', hex: '#ffb347', category: 'Orange' },
  { name: 'Mandarin', hex: '#f37a48', category: 'Orange' },
  { name: 'Mango', hex: '#ffcc5c', category: 'Orange' },
  { name: 'Mango tango', hex: '#ff8243', category: 'Orange' },
  { name: 'Melon', hex: '#fdbcb4', category: 'Orange' },
  { name: 'Neon orange', hex: '#ff6700', category: 'Orange' },
  { name: 'Orange', hex: '#ffa500', category: 'Orange' },
  { name: 'Orange peel', hex: '#ff9f00', category: 'Orange' },
  { name: 'Orange red', hex: '#ff4500', category: 'Orange' },
  { name: 'Papaya', hex: '#ff9f00', category: 'Orange' },
  { name: 'Papaya whip', hex: '#ffefd5', category: 'Orange' },
  { name: 'Pastel orange', hex: '#ffb347', category: 'Orange' },
  { name: 'Peach', hex: '#ffcba4', category: 'Orange' },
  { name: 'Peach orange', hex: '#ffcc99', category: 'Orange' },
  { name: 'Peach puff', hex: '#ffdab9', category: 'Orange' },
  { name: 'Persian orange', hex: '#d99058', category: 'Orange' },
  { name: 'Persimmon', hex: '#ec5800', category: 'Orange' },
  { name: 'Portland orange', hex: '#ff5a36', category: 'Orange' },
  { name: 'Princeton orange', hex: '#f58025', category: 'Orange' },
  { name: 'Pumpkin', hex: '#ff7518', category: 'Orange' },
  { name: 'Red orange', hex: '#ff5349', category: 'Orange' },
  { name: 'Rust', hex: '#b7410e', category: 'Orange' },
  { name: 'Safety orange', hex: '#ff6600', category: 'Orange' },
  { name: 'Sandy brown', hex: '#f4a460', category: 'Orange' },
  { name: 'Sunset orange', hex: '#fd5e53', category: 'Orange' },
  { name: 'Tangerine', hex: '#f28500', category: 'Orange' },
  { name: 'Tiger orange', hex: '#fd6a02', category: 'Orange' },
  { name: 'Vivid orange', hex: '#ff5f00', category: 'Orange' }
];