import { ColorItem } from '../colorData';

export const pinkColors: ColorItem[] = [
  { name: 'Amaranth pink', hex: '#f19cbb', category: 'Pink' },
  { name: 'Ballet slipper', hex: '#ffeef5', category: 'Pink' },
  { name: 'Blush', hex: '#de5d83', category: 'Pink' },
  { name: 'Brink pink', hex: '#fb607f', category: 'Pink' },
  { name: 'Bubble gum', hex: '#ffc1cc', category: 'Pink' },
  { name: 'Cameo pink', hex: '#efbbcc', category: 'Pink' },
  { name: 'Carnation pink', hex: '#ffa6c9', category: 'Pink' },
  { name: 'Cerise pink', hex: '#ec3b83', category: 'Pink' },
  { name: 'Cherry blossom pink', hex: '#ffb7c5', category: 'Pink' },
  { name: 'China pink', hex: '#de6fa1', category: 'Pink' },
  { name: 'Cotton candy', hex: '#ffbcd9', category: 'Pink' },
  { name: 'Deep pink', hex: '#ff1493', category: 'Pink' },
  { name: 'Dusty pink', hex: '#dc9fb4', category: 'Pink' },
  { name: 'Flamingo pink', hex: '#fc8eac', category: 'Pink' },
  { name: 'French pink', hex: '#fd6c9e', category: 'Pink' },
  { name: 'French rose', hex: '#f64a8a', category: 'Pink' },
  { name: 'Fuchsia pink', hex: '#ff77ff', category: 'Pink' },
  { name: 'Hot pink', hex: '#ff69b4', category: 'Pink' },
  { name: 'Light pink', hex: '#ffb6c1', category: 'Pink' },
  { name: 'Magenta pink', hex: '#cc338b', category: 'Pink' },
  { name: 'Magenta rose', hex: '#ff00af', category: 'Pink' },
  { name: 'Misty rose', hex: '#ffe4e1', category: 'Pink' },
  { name: 'Mauvelous', hex: '#ef98aa', category: 'Pink' },
  { name: 'Orchid pink', hex: '#f2bdcd', category: 'Pink' },
  { name: 'Pale pink', hex: '#fadadd', category: 'Pink' },
  { name: 'Pastel pink', hex: '#dea5a4', category: 'Pink' },
  { name: 'Peach pink', hex: '#fadfad', category: 'Pink' },
  { name: 'Persian pink', hex: '#f77fbe', category: 'Pink' },
  { name: 'Pink', hex: '#ffc0cb', category: 'Pink' },
  { name: 'Pink flamingo', hex: '#fc74fd', category: 'Pink' },
  { name: 'Pink pearl', hex: '#e7accf', category: 'Pink' },
  { name: 'Pink sherbet', hex: '#f78fa7', category: 'Pink' },
  { name: 'Powder pink', hex: '#ffb3ba', category: 'Pink' },
  { name: 'Princess pink', hex: '#ffc6d2', category: 'Pink' },
  { name: 'Rose', hex: '#ff007f', category: 'Pink' },
  { name: 'Rose pink', hex: '#ff66cc', category: 'Pink' },
  { name: 'Rosy brown', hex: '#bc8f8f', category: 'Pink' },
  { name: 'Ruby pink', hex: '#e0115f', category: 'Pink' },
  { name: 'Salmon pink', hex: '#ff91a4', category: 'Pink' },
  { name: 'Shocking pink', hex: '#fc0fc0', category: 'Pink' },
  { name: 'Strawberry', hex: '#fc5a8d', category: 'Pink' },
  { name: 'Thulian pink', hex: '#de6fa1', category: 'Pink' },
  { name: 'Tickle me pink', hex: '#fc89ac', category: 'Pink' },
  { name: 'Ultra pink', hex: '#ff6fff', category: 'Pink' },
  { name: 'Watermelon', hex: '#ff7f7f', category: 'Pink' }
];