import { ColorItem } from '../colorData';

export const redColors: ColorItem[] = [
  { name: 'Amaranth', hex: '#e52b50', category: 'Red' },
  { name: 'Amaranth purple', hex: '#ab274f', category: 'Red' },
  { name: 'Barn red', hex: '#7c0a02', category: 'Red' },
  { name: 'Bittersweet', hex: '#ff6347', category: 'Red' },
  { name: 'Bittersweet shimmer', hex: '#bf4f36', category: 'Red' },
  { name: 'Blood red', hex: '#660000', category: 'Red' },
  { name: 'Brick red', hex: '#cb4154', category: 'Red' },
  { name: 'Bright pink (Crayola)', hex: '#ff007f', category: 'Red' },
  { name: 'Burgundy', hex: '#800020', category: 'Red' },
  { name: 'Cadmium red', hex: '#e30022', category: 'Red' },
  { name: 'Candy apple red', hex: '#ff0800', category: 'Red' },
  { name: 'Cantaloupe melon', hex: '#fdbcb4', category: 'Red' },
  { name: 'Cardinal', hex: '#c41e3a', category: 'Red' },
  { name: 'Carmine', hex: '#960018', category: 'Red' },
  { name: 'Carmine pink', hex: '#eb4c42', category: 'Red' },
  { name: 'Carnelian', hex: '#b31b1b', category: 'Red' },
  { name: 'Cerise', hex: '#de3163', category: 'Red' },
  { name: 'Cherry', hex: '#de3163', category: 'Red' },
  { name: 'Cherry red', hex: '#d2001f', category: 'Red' },
  { name: 'Chestnut red', hex: '#bc3f4a', category: 'Red' },
  { name: 'Chili red', hex: '#c21807', category: 'Red' },
  { name: 'Chinese red', hex: '#aa381e', category: 'Red' },
  { name: 'Chocolate cosmos', hex: '#58111a', category: 'Red' },
  { name: 'Cinnabar', hex: '#e34234', category: 'Red' },
  { name: 'Claret', hex: '#7f1734', category: 'Red' },
  { name: 'Cochineal', hex: '#8c2d19', category: 'Red' },
  { name: 'Coquelicot', hex: '#ff3800', category: 'Red' },
  { name: 'Coral', hex: '#ff7f50', category: 'Red' },
  { name: 'Coral pink', hex: '#f88379', category: 'Red' },
  { name: 'Coral red', hex: '#ff4040', category: 'Red' },
  { name: 'Cordovan', hex: '#893f45', category: 'Red' },
  { name: 'Cornell red', hex: '#b31b1b', category: 'Red' },
  { name: 'Crimson', hex: '#dc143c', category: 'Red' },
  { name: 'Crimson glory', hex: '#be0032', category: 'Red' },
  { name: 'Dark coral', hex: '#cd5b45', category: 'Red' },
  { name: 'Dark red', hex: '#8b0000', category: 'Red' },
  { name: 'Dark salmon', hex: '#e9967a', category: 'Red' },
  { name: 'Dark scarlet', hex: '#560319', category: 'Red' },
  { name: 'Deep carmine', hex: '#a9203e', category: 'Red' },
  { name: 'Deep red', hex: '#850101', category: 'Red' },
  { name: 'English red', hex: '#ab4b52', category: 'Red' },
  { name: 'Falu red', hex: '#801818', category: 'Red' },
  { name: 'Ferrari red', hex: '#ff2800', category: 'Red' },
  { name: 'Fire brick', hex: '#b22222', category: 'Red' },
  { name: 'Fire engine red', hex: '#ce2029', category: 'Red' },
  { name: 'Flame', hex: '#e25822', category: 'Red' },
  { name: 'Flamingo pink', hex: '#fc8eac', category: 'Red' },
  { name: 'Folly', hex: '#ff004f', category: 'Red' },
  { name: 'Fuzzy wuzzy', hex: '#cc6666', category: 'Red' },
  { name: 'Garnet', hex: '#733635', category: 'Red' },
  { name: 'Geranium', hex: '#c1272d', category: 'Red' },
  { name: 'Hibiscus', hex: '#b43757', category: 'Red' },
  { name: 'Imperial red', hex: '#ed2939', category: 'Red' },
  { name: 'Indian red', hex: '#cd5c5c', category: 'Red' },
  { name: 'Jasper', hex: '#d73502', category: 'Red' },
  { name: 'Light coral', hex: '#f08080', category: 'Red' },
  { name: 'Light red', hex: '#ffcccb', category: 'Red' },
  { name: 'Light salmon', hex: '#ffa07a', category: 'Red' },
  { name: 'Madder', hex: '#cc0000', category: 'Red' },
  { name: 'Mahogany', hex: '#c04000', category: 'Red' },
  { name: 'Maroon', hex: '#800000', category: 'Red' },
  { name: 'Medium carmine', hex: '#af4035', category: 'Red' },
  { name: 'Misty rose', hex: '#ffe4e1', category: 'Red' },
  { name: 'Neon red', hex: '#ff073a', category: 'Red' },
  { name: 'Off Red (RGB)', hex: '#ff0040', category: 'Red' },
  { name: 'Old rose', hex: '#c08081', category: 'Red' },
  { name: 'Old crimson', hex: '#9c2542', category: 'Red' },
  { name: 'Opera mauve', hex: '#b784a7', category: 'Red' },
  { name: 'Oxblood', hex: '#4a0e0e', category: 'Red' },
  { name: 'Pastel red', hex: '#ff6961', category: 'Red' },
  { name: 'Penn red', hex: '#9e1316', category: 'Red' },
  { name: 'Persian red', hex: '#cc3333', category: 'Red' },
  { name: 'Pink', hex: '#ffc0cb', category: 'Red' },
  { name: 'Pomegranate', hex: '#f34723', category: 'Red' },
  { name: 'Poppy', hex: '#ec5800', category: 'Red' },
  { name: 'Raspberry', hex: '#e30b5c', category: 'Red' },
  { name: 'Red', hex: '#ff0000', category: 'Red' },
  { name: 'Red Brown', hex: '#a52a2a', category: 'Red' },
  { name: 'Red devil', hex: '#860111', category: 'Red' },
  { name: 'Red (CMYK)', hex: '#ed1c24', category: 'Red' },
  { name: 'Red (Crayola)', hex: '#ee204d', category: 'Red' },
  { name: 'Red (Munsell)', hex: '#f2003c', category: 'Red' },
  { name: 'Rose red', hex: '#c21e56', category: 'Red' },
  { name: 'Ruby', hex: '#e0115f', category: 'Red' },
  { name: 'Rusty red', hex: '#da2c43', category: 'Red' },
  { name: 'Scarlet', hex: '#ff2400', category: 'Red' },
  { name: 'Tomato', hex: '#ff6347', category: 'Red' },
  { name: 'Turkey red', hex: '#a91101', category: 'Red' },
  { name: 'Vermilion', hex: '#e34234', category: 'Red' },
  { name: 'Wine', hex: '#722f37', category: 'Red' }
];