import { ColorItem } from '../colorData';

export const turquoiseColors: ColorItem[] = [
  { name: 'Aqua', hex: '#00ffff', category: 'Turquoise' },
  { name: 'Aquamarine', hex: '#7fffd4', category: 'Turquoise' },
  { name: 'Bright turquoise', hex: '#08e8de', category: 'Turquoise' },
  { name: 'Cadet blue', hex: '#5f9ea0', category: 'Turquoise' },
  { name: 'Celeste', hex: '#b2ffff', category: 'Turquoise' },
  { name: 'Cyan', hex: '#00ffff', category: 'Turquoise' },
  { name: 'Dark cyan', hex: '#008b8b', category: 'Turquoise' },
  { name: 'Dark turquoise', hex: '#00ced1', category: 'Turquoise' },
  { name: 'Electric blue', hex: '#7df9ff', category: 'Turquoise' },
  { name: 'Light blue', hex: '#add8e6', category: 'Turquoise' },
  { name: 'Light cyan', hex: '#e0ffff', category: 'Turquoise' },
  { name: 'Light sea green', hex: '#20b2aa', category: 'Turquoise' },
  { name: 'Medium aquamarine', hex: '#66ddaa', category: 'Turquoise' },
  { name: 'Medium turquoise', hex: '#48d1cc', category: 'Turquoise' },
  { name: 'Pale turquoise', hex: '#afeeee', category: 'Turquoise' },
  { name: 'Powder blue', hex: '#b0e0e6', category: 'Turquoise' },
  { name: 'Robin egg blue', hex: '#00cccc', category: 'Turquoise' },
  { name: 'Sea green', hex: '#2e8b57', category: 'Turquoise' },
  { name: 'Teal', hex: '#008080', category: 'Turquoise' },
  { name: 'Tiffany blue', hex: '#0abab5', category: 'Turquoise' },
  { name: 'Turquoise', hex: '#40e0d0', category: 'Turquoise' },
  { name: 'Turquoise blue', hex: '#00ffef', category: 'Turquoise' },
  { name: 'Turquoise green', hex: '#a0d6b4', category: 'Turquoise' },
  { name: 'Verdigris', hex: '#43b3ae', category: 'Turquoise' },
  { name: 'Viridian', hex: '#40826d', category: 'Turquoise' },
  { name: 'Waterspout', hex: '#a4f4f9', category: 'Turquoise' },
  { name: 'Blue green', hex: '#0d98ba', category: 'Turquoise' },
  { name: 'Caribbean green', hex: '#00cc99', category: 'Turquoise' },
  { name: 'Cerulean', hex: '#007ba7', category: 'Turquoise' },
  { name: 'Dark sea green', hex: '#8fbc8f', category: 'Turquoise' },
  { name: 'Jade', hex: '#00a86b', category: 'Turquoise' },
  { name: 'Mint', hex: '#3eb489', category: 'Turquoise' },
  { name: 'Persian green', hex: '#00a693', category: 'Turquoise' },
  { name: 'Pine green', hex: '#01796f', category: 'Turquoise' },
  { name: 'Steel teal', hex: '#5f8a8b', category: 'Turquoise' }
];