import { ColorItem } from '../colorData';

export const violetColors: ColorItem[] = [
  { name: 'African violet', hex: '#b284be', category: 'Violet' },
  { name: 'Amethyst', hex: '#9966cc', category: 'Violet' },
  { name: 'Blue violet', hex: '#8a2be2', category: 'Violet' },
  { name: 'Byzantium', hex: '#702963', category: 'Violet' },
  { name: 'Dark magenta', hex: '#8b008b', category: 'Violet' },
  { name: 'Dark orchid', hex: '#9932cc', category: 'Violet' },
  { name: 'Dark purple', hex: '#301934', category: 'Violet' },
  { name: 'Dark slate blue', hex: '#483d8b', category: 'Violet' },
  { name: 'Dark violet', hex: '#9400d3', category: 'Violet' },
  { name: 'Deep lilac', hex: '#9955bb', category: 'Violet' },
  { name: 'Deep magenta', hex: '#cc00cc', category: 'Violet' },
  { name: 'Electric purple', hex: '#bf00ff', category: 'Violet' },
  { name: 'Eggplant', hex: '#614051', category: 'Violet' },
  { name: 'French lilac', hex: '#86608e', category: 'Violet' },
  { name: 'Fuchsia', hex: '#ff00ff', category: 'Violet' },
  { name: 'Grape', hex: '#6f2da8', category: 'Violet' },
  { name: 'Heliotrope', hex: '#df73ff', category: 'Violet' },
  { name: 'Imperial purple', hex: '#602f6b', category: 'Violet' },
  { name: 'Indigo', hex: '#4b0082', category: 'Violet' },
  { name: 'Lavender', hex: '#e6e6fa', category: 'Violet' },
  { name: 'Lavender blush', hex: '#fff0f5', category: 'Violet' },
  { name: 'Lavender purple', hex: '#967bb6', category: 'Violet' },
  { name: 'Light purple', hex: '#b19cd9', category: 'Violet' },
  { name: 'Lilac', hex: '#c8a2c8', category: 'Violet' },
  { name: 'Magenta', hex: '#ff00ff', category: 'Violet' },
  { name: 'Mauve', hex: '#e0b0ff', category: 'Violet' },
  { name: 'Medium orchid', hex: '#ba55d3', category: 'Violet' },
  { name: 'Medium purple', hex: '#9370db', category: 'Violet' },
  { name: 'Medium slate blue', hex: '#7b68ee', category: 'Violet' },
  { name: 'Medium violet red', hex: '#c71585', category: 'Violet' },
  { name: 'Mulberry', hex: '#c54b8c', category: 'Violet' },
  { name: 'Orchid', hex: '#da70d6', category: 'Violet' },
  { name: 'Pale violet red', hex: '#db7093', category: 'Violet' },
  { name: 'Pansy purple', hex: '#78184a', category: 'Violet' },
  { name: 'Pastel purple', hex: '#b39eb5', category: 'Violet' },
  { name: 'Periwinkle', hex: '#ccccff', category: 'Violet' },
  { name: 'Persian indigo', hex: '#32127a', category: 'Violet' },
  { name: 'Plum', hex: '#dda0dd', category: 'Violet' },
  { name: 'Purple', hex: '#800080', category: 'Violet' },
  { name: 'Purple heart', hex: '#69359c', category: 'Violet' },
  { name: 'Rebecca purple', hex: '#663399', category: 'Violet' },
  { name: 'Red violet', hex: '#c71585', category: 'Violet' },
  { name: 'Royal purple', hex: '#7851a9', category: 'Violet' },
  { name: 'Slate blue', hex: '#6a5acd', category: 'Violet' },
  { name: 'Thistle', hex: '#d8bfd8', category: 'Violet' },
  { name: 'Tyrian purple', hex: '#66023c', category: 'Violet' },
  { name: 'Violet', hex: '#ee82ee', category: 'Violet' },
  { name: 'Violet red', hex: '#f75394', category: 'Violet' },
  { name: 'Wisteria', hex: '#c9a0dc', category: 'Violet' },
  { name: 'Wood violet', hex: '#674c47', category: 'Violet' },
  { name: 'Xanadu', hex: '#738678', category: 'Violet' }
];