import { ColorItem } from '../colorData';

export const yellowColors: ColorItem[] = [
  { name: 'Aureolin', hex: '#fdee00', category: 'Yellow' },
  { name: 'Banana yellow', hex: '#ffe135', category: 'Yellow' },
  { name: 'Buff', hex: '#f0dc82', category: 'Yellow' },
  { name: 'Butter', hex: '#ffdb58', category: 'Yellow' },
  { name: 'Canary', hex: '#ffef00', category: 'Yellow' },
  { name: 'Canary yellow', hex: '#ffef00', category: 'Yellow' },
  { name: 'Champagne', hex: '#fad5a5', category: 'Yellow' },
  { name: 'Chartreuse', hex: '#7fff00', category: 'Yellow' },
  { name: 'Chrome yellow', hex: '#ffa700', category: 'Yellow' },
  { name: 'Citrine', hex: '#e4d00a', category: 'Yellow' },
  { name: 'Citron', hex: '#9fa91f', category: 'Yellow' },
  { name: 'Corn', hex: '#fbec5d', category: 'Yellow' },
  { name: 'Cream', hex: '#fffdd0', category: 'Yellow' },
  { name: 'Daffodil', hex: '#ffff31', category: 'Yellow' },
  { name: 'Dark goldenrod', hex: '#b8860b', category: 'Yellow' },
  { name: 'Dark khaki', hex: '#bdb76b', category: 'Yellow' },
  { name: 'Electric lime', hex: '#ccff00', category: 'Yellow' },
  { name: 'Electric yellow', hex: '#ffff33', category: 'Yellow' },
  { name: 'Flax', hex: '#eedc82', category: 'Yellow' },
  { name: 'Flavescent', hex: '#f7e98e', category: 'Yellow' },
  { name: 'Gold', hex: '#ffd700', category: 'Yellow' },
  { name: 'Golden yellow', hex: '#ffdf00', category: 'Yellow' },
  { name: 'Goldenrod', hex: '#daa520', category: 'Yellow' },
  { name: 'Honey', hex: '#feb811', category: 'Yellow' },
  { name: 'Icterine', hex: '#fcf75e', category: 'Yellow' },
  { name: 'Ivory', hex: '#fffff0', category: 'Yellow' },
  { name: 'Jasmine', hex: '#f8de7e', category: 'Yellow' },
  { name: 'Jonquil', hex: '#fada5e', category: 'Yellow' },
  { name: 'Khaki', hex: '#f0e68c', category: 'Yellow' },
  { name: 'Lemon', hex: '#fff700', category: 'Yellow' },
  { name: 'Lemon chiffon', hex: '#fffacd', category: 'Yellow' },
  { name: 'Light goldenrod', hex: '#fafad2', category: 'Yellow' },
  { name: 'Light yellow', hex: '#ffffe0', category: 'Yellow' },
  { name: 'Lime', hex: '#bfff00', category: 'Yellow' },
  { name: 'Maize', hex: '#fbec5d', category: 'Yellow' },
  { name: 'Mellow yellow', hex: '#f8de7e', category: 'Yellow' },
  { name: 'Mimosa', hex: '#efc050', category: 'Yellow' },
  { name: 'Mustard', hex: '#ffdb58', category: 'Yellow' },
  { name: 'Naples yellow', hex: '#fada5e', category: 'Yellow' },
  { name: 'Navajo white', hex: '#ffdead', category: 'Yellow' },
  { name: 'Old gold', hex: '#cfb53b', category: 'Yellow' },
  { name: 'Pale goldenrod', hex: '#eee8aa', category: 'Yellow' },
  { name: 'Peach yellow', hex: '#fadfad', category: 'Yellow' },
  { name: 'Pear', hex: '#d1e231', category: 'Yellow' },
  { name: 'Royal yellow', hex: '#fada5e', category: 'Yellow' },
  { name: 'Saffron', hex: '#f4c430', category: 'Yellow' },
  { name: 'School bus yellow', hex: '#ffd800', category: 'Yellow' },
  { name: 'Straw', hex: '#e4d96f', category: 'Yellow' },
  { name: 'Vanilla', hex: '#f3e5ab', category: 'Yellow' },
  { name: 'Wheat', hex: '#f5deb3', category: 'Yellow' },
  { name: 'Yellow', hex: '#ffff00', category: 'Yellow' }
];